Feature/lef 228 migrate sharepoint api module over to
friggframework/frigg pull request #161
Opened 2023-05-25 22:10 UTC by roboli

Some observations:

* I decided to omit testing Auth flow since this better be tested at the parent class, otherwise every module will have to test same functionality again and again, unless there are some specifics to current api module but I don't see that with this one.

* Same with methods, tests are only for current class/instance, other methods should be tested with parent class tests.

* I decided to use `nock` instead of `msw` since `nock` is good enough for mocking and `msw` basically replaces a backend server. So `nock` lighter IMHO.

2023-05-25 22:18 UTC, roboli reviewed
Left some comments @seanspeaks

2023-05-25 22:18 UTC, roboli commented on api-module-library/sharepoint/api.js
> +    getAuthUri() {
I removed `async` from here

2023-05-25 22:18 UTC, roboli commented on api-module-library/sharepoint/manager.js
> +            throw new Error(message);
An error is being thrown now.

And replaced the `portalId` reference which came from nowhere, with `externalId`

2023-05-30 06:27 UTC, seanspeaks requested changes
Some small changes, mostly documentation oriented. One functional in the processAuthorizationCallback method on the manager. 

Mostly looks great and really appreciate the thoroughness of the unit tests. 👌

2023-05-30 06:27 UTC, seanspeaks commented on api-module-library/sharepoint/LICENSE.md
> +Copyright (c) 2022 Left Hook Inc.
Can you modify to 2023?

2023-05-30 06:27 UTC, seanspeaks commented on api-module-library/sharepoint/README.md
> +This is the API Module for salesforce that allows the [Frigg](https://friggframework.org) code to talk to the salesforce API.
This was a copy/paste oopsie

Should say Microsoft SharePoint

2023-05-30 06:27 UTC, seanspeaks commented on api-module-library/sharepoint/README.md
> +Read more on the [Frigg documentation site](https://docs.friggframework.org/api-modules/list/salesforce
You can set the link to microsoft-sharepoint (even though the page doesn't yet exist)

2023-05-30 06:27 UTC, seanspeaks commented on api-module-library/sharepoint/defaultConfig.json
> +    "description": "If you know, you know"
Can you grab Microsoft's description of SharePoint from somewhere? Maybe the H1 of the product site? One or two sentences is fine

2023-05-30 06:27 UTC, seanspeaks commented on api-module-library/sharepoint/jest-env
> +SHAREPOINT_SCOPE=sharepoint_scope_test
What's this file?

I think I want to move towards .env for actual test runs (loaded with dotenv) and .env.example for collaboration purposes

2023-06-02 17:55 UTC, roboli commented on api-module-library/sharepoint/manager.test.js
> +    describe('#processAuthorizationCallback', () => {
Sorry, missed this @seanspeaks. Yeah, means a method test. I can't remember from where or when I started using it but it stuck

2023-06-05 16:23 UTC, seanspeaks approved these changes
Looks good to me; I would love for @MichaelRyanWebber To review it as well, specifically because you both have now worked on/reviewed a Microsoft Graph API-based api module, and you're both now heavily involved in API module development.

@roboli you should still merge and deploy this, but @MichaelRyanWebber Worth taking a look and noting either here or in a different issue/thread the differences between your work and Roberto's, and then let's see if we can coalesce around a standard (if there are obvious differences... otherwise, if we've already coalesced or if there are ideas to borrow between multiple, awesome, let's propagate.)

2023-06-05 16:42 UTC, merged