add types
friggframework/frigg pull request #165
Opened 2023-05-26 15:02 UTC by Fibii

Adds TS types for `./packages`

2023-06-06 15:14 UTC, leofmds requested changes

2023-06-20 17:52 UTC, seanspeaks commented on packages/types/package.json
@leofmds Can we just do this ourselves? (and merge in)

2023-06-20 22:04 UTC, leofmds commented on packages/types/package.json
@seanspeaks Sure, I can do it

2023-07-04 18:34 UTC, leofmds approved these changes

2023-07-04 18:34 UTC, merged

2023-07-05 14:00 UTC, seanspeaks commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@friggframework/api-module-microsoft-sharepoint@0.0.5`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-microsoft-sharepoint%400.0.5), [`@friggframework/types@0.1.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/types%400.1.1) :rocket:

2023-07-05 18:12 UTC, seanspeaks commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@friggframework/api-module-frontify@0.0.10`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%400.0.10) :rocket: