API listCollections
friggframework/frigg pull request #207
Opened 2023-07-31 23:21 UTC by msalvatti

2023-08-02 13:30 UTC, leofmds requested changes
LGTM, just a small change

2023-08-02 17:14 UTC, msalvatti commented on api-module-library/frontify/api.js
> +                          name
ok, included.

2023-08-03 22:55 UTC, leofmds approved these changes
👍🏻

2023-08-04 14:08 UTC, roboli approved these changes

2023-08-07 18:09 UTC, merged

2023-08-07 18:11 UTC, seanspeaks commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@friggframework/api-module-frontify@0.0.17`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%400.0.17) :rocket: