Feature/Add Sharepoint graphSearchQuery function
friggframework/frigg pull request #217
Opened 2023-08-27 20:38 UTC by msalvatti

Add Sharepoint graphSearchQuery function

2023-08-29 10:24 UTC, leofmds requested changes
Looks good, just add a missing test to the function and remove unnecessary log

2023-08-29 10:24 UTC, leofmds commented on api-module-library/frontify/api.test.js
> +                    console.log(buildQl())
Remove log

2023-08-29 10:24 UTC, leofmds commented on api-module-library/sharepoint/api.js
> +    async graphSearchQuery(query) {
Can you please add a test for this function?

2023-09-06 13:44 UTC, leofmds approved these changes
👍🏻

2023-09-06 14:00 UTC, merged

2023-09-06 14:01 UTC, seanspeaks commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`@friggframework/api-module-frontify@1.0.2`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%401.0.2), [`@friggframework/api-module-microsoft-sharepoint@0.0.8`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-microsoft-sharepoint%400.0.8) :rocket: